services:
  eureka-discovery-service:
    container_name: eureka-discovery-service
    build:
      context: ../eureka-discovery-service

  gateway-service:
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: ../gateway-service
    depends_on:
      eureka-discovery-service:
        condition: service_started