services:
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    ports:
      - "8090:8090"
    networks:
      - backend
    depends_on:
      eureka-discovery-service:
        condition: service_started
    volumes:
      - ../../../Tools/docker/volumes/keycloak/data/h2/:/opt/keycloak/data/h2

  eureka-discovery-service:
    container_name: eureka-discovery-service
    build:
      context: ../eureka-discovery-service
    ports:
      - "8081:8081"
    networks:
      - backend

  gateway-service:
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: ../gateway-service
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      keycloak:
        condition: service_started
      eureka-discovery-service:
        condition: service_started

  user-service:
    container_name: user-service
    #    environment:
    #      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: ../user-service
    networks:
      - backend
    depends_on:
      gateway-service:
        condition: service_started
      eureka-discovery-service:
        condition: service_started

networks:
  backend:
    driver: bridge
