services:
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    ports:
      - "8081:8082"
    networks:
      network:
    depends_on:
      eureka-discovery-service:
        condition: service_started
    volumes:
      - ../../../Tools/docker/volumes/keycloak/data/h2/:/opt/keycloak/data/h2

  eureka-discovery-service:
    container_name: eureka-discovery-service
    build:
      context: ../eureka-discovery-service

  gateway-service:
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: ../gateway-service
    ports:
      - "8080:8080"
    depends_on:
      keycloak:
        condition: service_started
      eureka-discovery-service:
        condition: service_started

networks:
  network:
    driver: bridge
