services:
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    ports:
      - "8081:8082"
    networks:
      network:
        ipv4_address: 192.168.100.2
    depends_on:
      eureka-discovery-service:
        condition: service_started

  eureka-discovery-service:
    container_name: eureka-discovery-service
    build:
      context: ../eureka-discovery-service

  gateway-service:
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: ../gateway-service
    depends_on:
      keycloak:
        condition: service_started
      eureka-discovery-service:
        condition: service_started

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
