services:
  config-service:
    container_name: config-service
    build:
      context: ../config-service
    ports:
      - "8888:8888"
    networks:
      - backend
    healthcheck:
      test: curl --fail --silent http://localhost:8888/actuator/health | grep UP || exit 1
      interval: 5s
      timeout: 5s
      retries: 2

  eureka-discovery-service:
    container_name: eureka-discovery-service
    build:
      context: ../eureka-discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend
    healthcheck:
      test: curl --fail --silent http://localhost:8761/actuator/health | grep UP || exit 1
      interval: 5s
      timeout: 5s
      retries: 2
    depends_on:
      config-service:
        condition: service_healthy

  keycloak:
    container_name: keycloak
    build:
      dockerfile: keycloak.Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ../../../Tools/docker/volumes/keycloak/data/h2/:/opt/keycloak/data/h2
    networks:
      - backend
    depends_on:
      eureka-discovery-service:
        condition: service_healthy

#  gateway-service:
#    container_name: gateway-service
#    build:
#      context: ../gateway-service
#    ports:
#      - "8080:8080"
#    networks:
#      - backend
#    depends_on:
#      keycloak:
#        condition: service_started
#      eureka-discovery-service:
#        condition: service_started
#
#  user-service:
#    container_name: user-service
#    #    environment:
#    #      - SPRING_PROFILES_ACTIVE=dev
#    build:
#      context: ../user-service
#    ports:
#      - "8081:8081"
#    networks:
#      - backend
#    depends_on:
#      gateway-service:
#        condition: service_started

networks:
  backend:
    driver: bridge